# Generated by Django 4.1.7 on 2023-03-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
                ('c_name', models.CharField(max_length=20)),
                ('c_conn_year', models.DateField()),
                ('c_status', models.CharField(choices=[('A', 'Active'), ('C', 'Ceased')], max_length=5)),
                ('c_add', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
    ]
