# Generated by Django 4.1.7 on 2023-03-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField()),
                ('e_name', models.CharField(max_length=20)),
                ('e_age', models.IntegerField()),
                ('e_doj', models.DateField()),
                ('e_role', models.CharField(choices=[('D', 'Developer'), ('T', 'Tester')], max_length=5)),
                ('e_add', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
